[build]
  command = "npm install && npx expo export --platform web"
  publish = "dist"

[build.environment]
  EXPO_PUBLIC_API_URL = "https://kmtvcscnositvsjbnpum.supabase.co/functions/v1"
  EXPO_PUBLIC_SUPABASE_URL = "https://kmtvcscnositvsjbnpum.supabase.co"
  EXPO_PUBLIC_SUPABASE_ANON_KEY = "sb_publishable_8upwc0TBfc-hGBe4iMhCNw_UFU1Ufbb"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200